### ISSUE TITLE
mention issues

### ISSUE THREAD

**Issue by YoshiyukiSakura** [opensquare-network/rich-text-editor#53]
### quilljs

- [x] can not mention at empty contents 
- [x] can not pree Enter to choose

### markdown

- [x] press `esc` to close the mention popup, not `Backspace`; case of **typo** #61 
- [x] do not `newLine` when selected(enter) a mention item #58 
- [x] reset the mention(suggestions) index #60 
- [x] #56 #62 
- [x] #66 
- [x] #67 #69 
- [x] #68 
- [x] maximize items #76
